# Generated by Django 4.2.16 on 2024-11-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_remove_task_due_date_project_end_date_task_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='required_role',
            field=models.CharField(default='frontend', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('designer', 'Diseñador'), ('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('qa', 'QA Engineer')], default='frontend', max_length=50),
        ),
    ]
