# Generated by Django 4.2.16 on 2024-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_project_priority_task_estimated_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='required_role',
            field=models.CharField(choices=[('designer', 'Diseñador'), ('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('qa', 'QA Engineer')], default='frontend', max_length=50),
        ),
    ]
